'use client'
import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import { Authenticator } from "@aws-amplify/ui-react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Pictures App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Authenticator.Provider>
          <div className="container">
            <Navbar />
            {children}
            <Footer />
          </div>
        </Authenticator.Provider>
      </body>
    </html>
  );
}
