/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-north-1",
    "aws_cognito_identity_pool_id": "eu-north-1:a40f645f-4839-435d-99fb-aba2bfcfc79a",
    "aws_cognito_region": "eu-north-1",
    "aws_user_pools_id": "eu-north-1_TWl3YzPb9",
    "aws_user_pools_web_client_id": "37buodu44u57gppbgf7kmpgf4f",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "picturesnextjsc8e44c475d2040f18e284907ea45b349143927-dev",
    "aws_user_files_s3_bucket_region": "eu-north-1"
};


export default awsmobile;
